services:
  backend:
    container_name: 5ers_backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - mynetwork

  dashboard:
    container_name: 5ers_dashboard
    build:
      context: ./dashboard
    ports:
      - "3001:3001"
    env_file:
      - ./dashboard/.env
    volumes:
      - ./dashboard:/app
    working_dir: /app
    command: npm start
    networks:
      - mynetwork
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: 5ers_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
